### ISSUE TITLE
파이선 3.10 버전 kobert 호환 문제

### ISSUE THREAD

**Issue by ChangZero** [ChangZero/koBERT-finetuning-demo#1]
최근에 colab으로 돌려보려했는데 문제 생겨서 확인해본 결과 파이썬 3.10이상부터 kobert가 잘안돌아감...
kobert 공식 github issue에 비슷한 오류 확인
https://github.com/SKTBrain/KoBERT/issues/102
따라해봤는데 여전히 안돌아감 ㅋ...
파이썬 3.10은 아직 최적화가 덜된듯함 ㅠ

**Comment by twkim00** [comment]
혹시 문제 해결하셨나요?

**Comment by ChangZero** [comment]
코랩에서 안돌아가던 문제 해결
- 허깅페이스 허브의 kobert 설치
- BERTSentenceTransforme 클래스 생성 -> nlp.data.BERTSentenceTransform에서 vocab 또는 type error 발생 해결
-> 자세한 내용은 해당 블로그 참고 https://blog.naver.com/newyearchive/223097878715
- get_kobert_model 선언


https://github.com/ChangZero/koBERT-finetuning-demo/blob/main/kobert_colab.ipynb
@twkim00 위 코드 한번 참고하시면 될거 같습니다.

**Comment by ChangZero** [comment]
혹시 해결 못하신 분들은 아래 코드 참고해보시면 좋을거 같습니다!
https://github.com/ChangZero/koBERT-finetuning-demo/blob/main/kobert_colab.ipynb
